### PR TITLE
Add review forms (front end only)

### PR DESCRIPTION
**Pull request by shreyabarua**
Add forms for reviewers and reviewees to sign up on ResumeBuddy

### CODE REVIEW

**Comment by shreyabarua** [comment]
@googlebot I signed it!

**Review by shayla11 — APPROVED** [review]
Looks good!

**Review by oydang — CHANGES_REQUESTED** [review]
The indentation formatting is off just by a little for all the .html files. Some use 3 space indentations (should be 2). If Cloud Shell auto-formatter isn't working for you, you could try this formatter: https://www.freeformatter.com/html-formatter.html

**Comment by oydang** [comment]
One last change: we don't want to commit files that are in `target/`. I recommend:

1. Pull from `googleinterns:master` by running `git pull upstream master` into this branch (`review-forms`). This will pull in the `.gitignore` file that Ani added.
2. Run `git rm -r --cached target/` to remove `target/` files from your index.
3. Commit and push.

**Review by oydang — APPROVED** [review]

**Pull request merged**
